{% set name = "RAiDER" %}
{% set version = "0.5.1" %}

package:
  # For multiple outputs, I'm mimicking: https://github.com/conda-forge/matplotlib-feedstock/blob/main/recipe/meta.yaml
  name: raider-suite
  version: {{ version }}

source:
  url: https://github.com/dbekaert/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f23e13b5e7d17c02e0248d6c14b0bc025310b8f70168237199c83c85c42c5685
  patches:
    - 604.diff  # ensure alaska.geojson.zip is being packaged; fixed in v0.4.6
    - 606.diff  # fix isce3 import to keep it optional; fixed in v0.4.6

build:
  number: 0

outputs:
  - name: raider-base
    script: build_base.sh
    build:
      skip: true  # [py<39 or win]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - cython                                 # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
        - pybind11                               # [build_platform != target_platform]
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake
      host:
        - python
        - pip
        - pybind11 >=2.5.0
        - setuptools >61.0
        - setuptools_scm >6.2
        - python-build
        - numpy
        - cython
      run:
        - python
        - asf_search
        - boto3
        - cdsapi
        - cfgrib
        - dask
        - dem_stitcher >=2.3.1
        - ecmwf-api-client
        - h5py
        - herbie-data
        - h5netcdf
        - hyp3lib
        - jsonschema==3.2.0
        - lxml
        - matplotlib-base
        - netcdf4
        - {{ pin_compatible('numpy') }}
        - pandas
        - progressbar
        - pydap >3.2.2
        - pyproj >=2.2.0
        - pyyaml
        - rasterio >=1.3.0
        - requests
        - rioxarray
        - s3fs
        - scipy>1.10.0
        - sentineleof
        - shapely
        - tqdm
    test:
      imports:
        - RAiDER
        - RAiDER.delay
        - RAiDER.interpolator
      requires:
        - pip
      commands:
        - pip check
        - raider.py -h
        - calcDelays.py -h
        - calcDelaysGUNW.py -h
        - raiderDownloadGNSS.py -h
        - downloadGNSS.py -h
        - generateGACOSVRT.py
        - raiderStats.py -h

  - name: raider
    build:
      skip: true  # [py<39 or win]
    requirements:
      host:
        - python
      run:
        - python
        - isce3 >=0.15.0
        - {{ pin_subpackage('raider-base', max_pin="x.x.x") }}
    test:
      imports:
        - RAiDER

about:
  home: https://github.com/dbekaert/RAiDER
  summary: Raytracing Atmospheric Delay Estimation for RADAR
  description: |
    RAiDER-tools is a package in Python which contains tools to calculate
    tropospheric corrections for Radar using a raytracing implementation.
    Its development was funded under the NASA Sea-level Change Team (NSLCT)
    program, the Earth Surface and Interior (ESI) program, and the NISAR
    Science Team (NISAR-ST) (NTR-51433). U.S. Government sponsorship acknowledged.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://github.com/dbekaert/RAiDER-docs
  dev_url: https://github.com/dbekaert/RAiDER

extra:
  recipe-maintainers:
    - jlmaurer
    - cmarshak
    - jhkennedy
