{% set name = "RAiDER" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dbekaert/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 96ccceb5cff1325ec0fb8ace02108d945042e22e4ccc59820f921f5178922911

build:
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
    - {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py<38 or win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - pip
    - pybind11 >=2.5.0
    - setuptools >61.0
    - setuptools_scm >6.2
    - wheel
    - numpy
    - cython

  run:
    - python
    - cdsapi
    - cfgrib
    - dask
    - dem_stitcher >=2.3.1
    - ecmwf-api-client
    - h5py
    - herbie-data
    - isce3 >=0.9.0
    - lxml
    - matplotlib-base
    - netcdf4
    - {{ pin_compatible('numpy') }}
    - pandas
    - progressbar
    - pydap >3.2.2
    - pyproj >=2.2.0
    - pyyaml
    - rasterio >=1.3.0
    - requests
    - s3fs
    - scipy
    - shapely
    - tqdm
    - xarray

test:
  imports:
    - RAiDER
    - RAiDER.delay
    - RAiDER.interpolator
  requires:
    - pip
  commands:
    - pip check
    - raider.py -h
    - calcDelays.py -h
    - calcDelaysGUNW.py -h
    - raiderDownloadGNSS.py -h
    - downloadGNSS.py -h
    - generateGACOSVRT.py
    - raiderStats.py -h

about:
  home: https://github.com/dbekaert/RAiDER
  summary: Raytracing Atmospheric Delay Estimation for RADAR
  description: |
    RAiDER-tools is a package in Python which contains tools to calculate
    tropospheric corrections for Radar using a raytracing implementation.
    Its development was funded under the NASA Sea-level Change Team (NSLCT)
    program, the Earth Surface and Interior (ESI) program, and the NISAR
    Science Team (NISAR-ST) (NTR-51433). U.S. Government sponsorship acknowledged.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://github.com/dbekaert/RAiDER-docs
  dev_url: https://github.com/dbekaert/RAiDER

extra:
  recipe-maintainers:
    - jlmaurer
    - cmarshak
    - jhkennedy
